name: Deploy DevOps IaC na AWS

on:
  push:
    branches:
      - main
      - fix/ci-cd-test

jobs:
  terraform-ansible-deploy:
    runs-on: ubuntu-latest
    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false
      TERRAFORM_WRAPPER_DISABLED: true
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
          terraform_wrapper: false

      - name: Verificar Versões das Ferramentas
        run: |
          echo "Terraform Version:"
          terraform --version
          echo "Ansible Version:"
          ansible --version

      - name: Iniciar e Validar o Terraform
        run: |
          terraform -chdir=terraform init
          terraform -chdir=terraform validate

      - name: Aplicar o Terraform
        run: terraform -chdir=terraform apply -auto-approve

      - name: Coletar e Exportar IP
        run: |
          RAW_OUTPUT=$(terraform -chdir=terraform output -json public_ip)
          CLEAN_IP=$(echo "$RAW_OUTPUT" | grep -oE '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -n 1)
          if [ -z "$CLEAN_IP" ]; then
            echo "Erro: sem ip valido"
            echo "Valor capturado: $RAW_OUTPUT"
            exit 1
          fi
          echo "PUBLIC_IP=$CLEAN_IP" >> $GITHUB_ENV
          echo "IP capturado: $CLEAN_IP"

      - name: Configurar SSH e Aguardar Subir a Instância
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
          echo "Aguardando o servidor SSH subir no IP ${{ env.PUBLIC_IP }}..."
          for i in {1..6}; do
            ssh-keyscan -H ${{ env.PUBLIC_IP }} >> ~/.ssh/known_hosts && break || \
            echo "Tentativa $i falhou, aguardando..." && sleep 10;
          done

      - name: Criar Inventário temporário para Rodar o Ansible
        run: |
          echo "[aws_servers]" > hosts.ini
          echo "${{ env.PUBLIC_IP }}" >> hosts.ini
          
          ansible-playbook -i hosts.ini ansible/setup.yml \
          -u ubuntu \
          --private-key ~/.ssh/id_rsa \
          --ssh-common-args='-o StrictHostKeyChecking=no' 2>&1

      - name: Encerramento do Provisionamento para Evitar Custos
        if: always()
        run: |
          echo "Infraestrutura ativa e rodando em: ${{ env.PUBLIC_IP }}"
          echo "Executando timer de 5 minutos para cancelamento do provisionamento..." 
          sleep 300
          echo "Encerrando o provisionamento para evitar custos adicionais..."
          terraform -chdir=terraform destroy -auto-approve